In [1]:
import sys
from pathlib import Path
import importlib
from dotenv import load_dotenv
from huggingface_hub import login
import os
import pandas as pd

In [2]:
# Search up the directory tree for 'src' directory
src_dir = None
for parent in Path.cwd().parents:
    candidate = parent / 'src'
    if candidate.exists():
        src_dir = candidate
        break

if src_dir is None:
    src_dir = Path.cwd() / 'src'  # fallback

sys.path.insert(0, str(src_dir))

import thesis.baselines.bert_classifier as bert

importlib.reload(bert)

from thesis.baselines.bert_classifier import run_baseline

In [3]:
scenarios = ["fox", "harrison", "russellmitchell", "santos", "shaw", "wardbeck", "wheeler", "wilson"]

dataset = "alerts_csv"

model_name = "distilbert/distilbert-base-uncased"

In [4]:
load_dotenv()
token = os.getenv("HF_TOKEN")
login(token=token)

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

In [5]:
for s in scenarios:
    run_baseline(dataset, s, model_name)

Running BERT baseline for scenario: fox
Splitting data into train/val/test with ratios: 0.8 0.1 0.2
Train size: 7217, Val size: 1031, Test size: 2062
Label distribution in each split:
Train: label
0    0.921158
1    0.078842
Name: proportion, dtype: float64
Val: label
0    0.921435
1    0.078565
Name: proportion, dtype: float64
Test: label
0    0.921435
1    0.078565
Name: proportion, dtype: float64
Loading tokenizer for model: distilbert/distilbert-base-uncased

Map:   0%|          | 0/7217 [00:00<?, ? examples/s]

Map:   0%|          | 0/1031 [00:00<?, ? examples/s]

Map:   0%|          | 0/2062 [00:00<?, ? examples/s]

Loading model: distilbert/distilbert-base-uncased

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert/distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

PyTorch version: 2.11.0
MPS built: True
MPS available: True
Using Apple GPU via MPS
Train and evaluate BERT model...

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].
/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing results to: /Users/annavisman/stack/TUDelft/thesis/msc-thesis/out/bert/alerts_csv/fox/results.txt
Done.
Running BERT baseline for scenario: harrison
Splitting data into train/val/test with ratios: 0.8 0.1 0.2
Train size: 24215, Val size: 3460, Test size: 6919
Label distribution in each split:
Train: label
0    0.95127
1    0.04873
Name: proportion, dtype: float64
Val: label
0    0.951156
1    0.048844
Name: proportion, dtype: float64
Test: label
0    0.951294
1    0.048706
Name: proportion, dtype: float64
Loading tokenizer for model: distilbert/distilbert-base-uncased

Map:   0%|          | 0/24215 [00:00<?, ? examples/s]

Map:   0%|          | 0/3460 [00:00<?, ? examples/s]

Map:   0%|          | 0/6919 [00:00<?, ? examples/s]

Loading model: distilbert/distilbert-base-uncased

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert/distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

PyTorch version: 2.11.0
MPS built: True
MPS available: True
Using Apple GPU via MPS
Train and evaluate BERT model...

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].
/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing results to: /Users/annavisman/stack/TUDelft/thesis/msc-thesis/out/bert/alerts_csv/harrison/results.txt
Done.
Running BERT baseline for scenario: russellmitchell
Splitting data into train/val/test with ratios: 0.8 0.1 0.2
Train size: 3914, Val size: 560, Test size: 1119
Label distribution in each split:
Train: label
0    0.967552
1    0.032448
Name: proportion, dtype: float64
Val: label
0    0.967857
1    0.032143
Name: proportion, dtype: float64
Test: label
0    0.967828
1    0.032172
Name: proportion, dtype: float64
Loading tokenizer for model: distilbert/distilbert-base-uncased

Map:   0%|          | 0/3914 [00:00<?, ? examples/s]

Map:   0%|          | 0/560 [00:00<?, ? examples/s]

Map:   0%|          | 0/1119 [00:00<?, ? examples/s]

Loading model: distilbert/distilbert-base-uncased

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert/distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

PyTorch version: 2.11.0
MPS built: True
MPS available: True
Using Apple GPU via MPS
Train and evaluate BERT model...

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].
/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing results to: /Users/annavisman/stack/TUDelft/thesis/msc-thesis/out/bert/alerts_csv/russellmitchell/results.txt
Done.
Running BERT baseline for scenario: santos
Splitting data into train/val/test with ratios: 0.8 0.1 0.2
Train size: 15778, Val size: 2254, Test size: 4508
Label distribution in each split:
Train: label
0    0.98593
1    0.01407
Name: proportion, dtype: float64
Val: label
0    0.985803
1    0.014197
Name: proportion, dtype: float64
Test: label
0    0.986025
1    0.013975
Name: proportion, dtype: float64
Loading tokenizer for model: distilbert/distilbert-base-uncased

Map:   0%|          | 0/15778 [00:00<?, ? examples/s]

Map:   0%|          | 0/2254 [00:00<?, ? examples/s]

Map:   0%|          | 0/4508 [00:00<?, ? examples/s]

Loading model: distilbert/distilbert-base-uncased

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert/distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

PyTorch version: 2.11.0
MPS built: True
MPS available: True
Using Apple GPU via MPS
Train and evaluate BERT model...

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].
/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing results to: /Users/annavisman/stack/TUDelft/thesis/msc-thesis/out/bert/alerts_csv/santos/results.txt
Done.
Running BERT baseline for scenario: shaw
Splitting data into train/val/test with ratios: 0.8 0.1 0.2
Train size: 7277, Val size: 1040, Test size: 2080
Label distribution in each split:
Train: label
0    0.985159
1    0.014841
Name: proportion, dtype: float64
Val: label
0    0.985577
1    0.014423
Name: proportion, dtype: float64
Test: label
0    0.985096
1    0.014904
Name: proportion, dtype: float64
Loading tokenizer for model: distilbert/distilbert-base-uncased

Map:   0%|          | 0/7277 [00:00<?, ? examples/s]

Map:   0%|          | 0/1040 [00:00<?, ? examples/s]

Map:   0%|          | 0/2080 [00:00<?, ? examples/s]

Loading model: distilbert/distilbert-base-uncased

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert/distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

PyTorch version: 2.11.0
MPS built: True
MPS available: True
Using Apple GPU via MPS
Train and evaluate BERT model...

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].
/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing results to: /Users/annavisman/stack/TUDelft/thesis/msc-thesis/out/bert/alerts_csv/shaw/results.txt
Done.
Running BERT baseline for scenario: wardbeck
Splitting data into train/val/test with ratios: 0.8 0.1 0.2
Train size: 8229, Val size: 1176, Test size: 2352
Label distribution in each split:
Train: label
0    0.986147
1    0.013853
Name: proportion, dtype: float64
Val: label
0    0.986395
1    0.013605
Name: proportion, dtype: float64
Test: label
0    0.986395
1    0.013605
Name: proportion, dtype: float64
Loading tokenizer for model: distilbert/distilbert-base-uncased

Map:   0%|          | 0/8229 [00:00<?, ? examples/s]

Map:   0%|          | 0/1176 [00:00<?, ? examples/s]

Map:   0%|          | 0/2352 [00:00<?, ? examples/s]

Loading model: distilbert/distilbert-base-uncased

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert/distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

PyTorch version: 2.11.0
MPS built: True
MPS available: True
Using Apple GPU via MPS
Train and evaluate BERT model...

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].
/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing results to: /Users/annavisman/stack/TUDelft/thesis/msc-thesis/out/bert/alerts_csv/wardbeck/results.txt
Done.
Running BERT baseline for scenario: wheeler
Splitting data into train/val/test with ratios: 0.8 0.1 0.2
Train size: 14686, Val size: 2098, Test size: 4197
Label distribution in each split:
Train: label
0    0.970789
1    0.029211
Name: proportion, dtype: float64
Val: label
0    0.970925
1    0.029075
Name: proportion, dtype: float64
Test: label
0    0.970932
1    0.029068
Name: proportion, dtype: float64
Loading tokenizer for model: distilbert/distilbert-base-uncased

Map:   0%|          | 0/14686 [00:00<?, ? examples/s]

Map:   0%|          | 0/2098 [00:00<?, ? examples/s]

Map:   0%|          | 0/4197 [00:00<?, ? examples/s]

Loading model: distilbert/distilbert-base-uncased

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert/distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

PyTorch version: 2.11.0
MPS built: True
MPS available: True
Using Apple GPU via MPS
Train and evaluate BERT model...

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].
/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing results to: /Users/annavisman/stack/TUDelft/thesis/msc-thesis/out/bert/alerts_csv/wheeler/results.txt
Done.
Running BERT baseline for scenario: wilson
Splitting data into train/val/test with ratios: 0.8 0.1 0.2
Train size: 18567, Val size: 2653, Test size: 5305
Label distribution in each split:
Train: label
0    0.954274
1    0.045726
Name: proportion, dtype: float64
Val: label
0    0.954391
1    0.045609
Name: proportion, dtype: float64
Test: label
0    0.954383
1    0.045617
Name: proportion, dtype: float64
Loading tokenizer for model: distilbert/distilbert-base-uncased

Map:   0%|          | 0/18567 [00:00<?, ? examples/s]

Map:   0%|          | 0/2653 [00:00<?, ? examples/s]

Map:   0%|          | 0/5305 [00:00<?, ? examples/s]

Loading model: distilbert/distilbert-base-uncased

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert/distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

PyTorch version: 2.11.0
MPS built: True
MPS available: True
Using Apple GPU via MPS
Train and evaluate BERT model...

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].
/Users/annavisman/stack/TUDelft/thesis/msc-thesis/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing results to: /Users/annavisman/stack/TUDelft/thesis/msc-thesis/out/bert/alerts_csv/wilson/results.txt
Done.

#### Metrics table

In [8]:
def collect_bert_results(results_root: str | Path) -> pd.DataFrame:
    """
    Collect all scenario-level BERT results from result files into one table.

    Expected structure:
        results_root/
            scenario_1/results.txt
            scenario_2/results.txt
            ...

    Each results.txt should contain lines like:
        accuracy: 0.9943
        precision: 1.0000
        recall: 0.8033
        f1: 0.8909
        ....

    Returns:
        DataFrame with columns:
        [scenario, accuracy, precision, recall, f1, tp, fp, tn, fn, pred_attack_count, pred_attack_rate, avg_attack_prob, max_attack_prob, min_attack_prob]
    """
    results_root = Path(results_root)
    rows = []

    for results_file in results_root.rglob("results.txt"):
        metrics = {}
        scenario = results_file.parent.name

        with open(results_file, "r") as f:
            for line in f:
                line = line.strip()
                if not line or ":" not in line:
                    continue

                key, value = line.split(":", 1)
                key = key.strip()
                value = value.strip()

                try:
                    metrics[key] = float(value)
                except ValueError:
                    metrics[key] = value

        row = {"scenario": scenario, **metrics}
        rows.append(row)

    df = pd.DataFrame(rows)

    metric_cols = ["accuracy", "precision", "recall", "f1", "tp", "fp", "tn", "fn", "pred_attack_count", "pred_attack_rate", "avg_attack_prob", "max_attack_prob", "min_attack_prob"]
    existing_cols = ["scenario"] + [c for c in metric_cols if c in df.columns]
    df = df[existing_cols].sort_values("scenario").reset_index(drop=True)

    return df

In [9]:
df = collect_bert_results("../../../out/bert/alerts_csv")
df.to_csv("../../../out/bert/alerts_csv/bert_results_summary.csv", index=False)